export default function Quotation() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen text-center px-4 space-y-10">
      
      {/* Quotation Block */}
      <div className="max-w-xl bg-[#c0d1e1] bg-opacity-60 p-6 rounded-2xl shadow-lg backdrop-blur-sm animate-fade-in">
        <p className="text-xl md:text-2xl font-semibold text-[#5c4d7d]">
          “You don’t have to control your thoughts. You just have to stop letting them control you.”
        </p>
        <p className="mt-2 text-sm text-gray-500">— Dan Millman</p>
      </div>

      {/* User Manual Block */}
      <div className="max-w-xl bg-[#c0d1e1] bg-opacity-60 p-6 rounded-2xl shadow-lg backdrop-blur-sm animate-fade-in">
        <h2 className="text-xl md:text-2xl font-semibold text-[#5c4d7d] mb-4">🧭 How to Use the App</h2>
        <ul className="text-left text-gray-700 text-sm md:text-base list-disc list-inside space-y-2">
          <li>📝 Log your daily thoughts and moods in the New Entry section provided on the Navbar.</li>
          <li>🌱 Get wellness tips and suggestions based on your average  mood score generated by AI.</li>
          <li>👥 Share your thoughts in the Community section to connect with others.</li>
          <li>🔐 Your data is private and secured — stored only for your well-being insights.</li>
        </ul>
      </div>

    </div>
  );
}
